$ANSIBLE_VAULT;1.1;AES256
66633763616431383134343734613439636134376439363236643763363330313462366264353933
6230396639656636316331623537373538643665333436620a333931626235323566333637343439
64383261666532333866333466386332636434666239343339323032613064643938313831633663
3137636439616134310a643663316138353566366534623064343762336262316334663464643364
36323636316530353763323337303265393364386332386363323562663961653161613935316663
31343839396663383835353133623065393962303461643466306237306233643732353538323565
31373663643334306234333731636634636434623937373865653337303831623164366137343730
33646336616636363831626437303231386438303661666537656435343364306630363038626439
37363332363264336138613937633262396131613737386461643964396339636563383037666466
31323933313466313538306430316165653836313566353639366531633230613835663732623434
31393137346662316435363261613531653534313937643735303730646661663263353537633963
39383031383037313535376635313133316638616230333539663165373662303137373164333465
36303961323533303632643234613236316238343536396230383362373333653135633666633065
39646435323966386335663834613633663964643334653564336162343466613763313961633831
363530326438333463666565376333393531
