$ANSIBLE_VAULT;1.1;AES256
63393536383561613961373062333339653335666330356637383831396564386533666338383733
6630366432333231363036613265313330333039616533360a613561313938363134313163386435
36616639663533346236626232303634666534623162626336393639303137373732666261383338
6364323362316564350a623139373230653465653539636632326336313265653633646535313035
35663931646238646633353064393732656634313034383636623465363261326538303962643831
38636562653362646132383533356634393065373737356466636530333235613366386663373933
62643136633832346163393333313664626138363664333162646131306132656561373731363135
36643833353634636638393362386530373037353966653536316530353638396566626331616233
39633136613766646664346164386131613064373439613562616265373363343661396232303436
30306562636662623934306534303332393736326339653463353064363466653733396631343536
36376338333161343437663065356337356566353934643462313937303137633434373238646262
64313238303964373961
