---
- name: Ensure folders exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ app_path }}"
    - "{{ local_mount_path }}"

- name: Check if docker compose file exists
  stat:
    path: "{{ docker_compose_path }}"
  register: docker_compose_file

- name: Ensure Docker Compose is stopped if the file exists
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    state: absent
  when: docker_compose_file.stat.exists

- name: Copy config file from the master node
  template:
    src: paperless.docker-compose.j2
    dest: "{{ docker_compose_path }}"

- name: Copy environment file from the master node
  template:
    src: paperless.env
    dest: "{{ env_file_path }}"

- name: Ensure Docker Compose is running
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    pull: missing
    state: present
    remove_orphans: true
