$ANSIBLE_VAULT;1.1;AES256
62383961386661633935316137343731336133326363353032323136373039633961323632366461
6433353736653366353939333738336163396631623766340a376331366335396231613137343738
33303264303766363138323833346164643037396134666563363365633164306465363064663766
6662653864633135640a643339313937343065613266656661386665666664353837643862353433
37313638373136333233306466633330366565663765623436323937623966646261326533643036
6439323265353037303031613539383430383836633431656330
