shell_profiles:
- "~/.bash_profile"
- "~/.zshrc"

script_dir: "~/.ansible_shell_scripts"

block_start_const: "# BEGIN_ANSIBLE_MANAGED_SHELL_ALIASES"
block_end_const: "# END_ANSIBLE_MANAGED_SHELL_ALIASES"
