$ANSIBLE_VAULT;1.1;AES256
30663964353738636332636531396539303536346666333761383362353436623365656364353634
3765313635656234396261313439663436383839616261640a336538353037333236336333363766
65303238373134393431613666633635373338363834656434623465653239656638656130623436
3436623632653236320a636465353231333230643032613134363665636431646232636232363561
37666461393263373837643661363066373263323132376361353663366362396464616334343137
30666135343731316435373664323338393337356434353238373565623739353536323535353366
38613466363636313532336535313963393439313834396361613138363633356235623237393431
39363761306538393530653661313162396532343034623131383431373365363761303936376166
32326165323137623838626463643830383565653961386666613737636365336536
